/**
 * Convert Slack-style emoji shortcodes to Unicode emojis.
 *
 * Slack sends emojis as shortcodes like :horse: instead of Unicode.
 * This converts common shortcodes to their Unicode equivalents.
 */

// Common emoji shortcode to Unicode mapping
// Based on Slack's standard emoji set
const EMOJI_MAP: Record<string, string> = {
	// Faces
	smile: "😄",
	laughing: "😆",
	blush: "😊",
	smiley: "😃",
	relaxed: "☺️",
	smirk: "😏",
	heart_eyes: "😍",
	kissing_heart: "😘",
	kissing_closed_eyes: "😚",
	flushed: "😳",
	relieved: "😌",
	satisfied: "😆",
	grin: "😁",
	wink: "😉",
	stuck_out_tongue_winking_eye: "😜",
	stuck_out_tongue_closed_eyes: "😝",
	grinning: "😀",
	kissing: "😗",
	kissing_smiling_eyes: "😙",
	stuck_out_tongue: "😛",
	sleeping: "😴",
	worried: "😟",
	frowning: "😦",
	anguished: "😧",
	open_mouth: "😮",
	grimacing: "😬",
	confused: "😕",
	hushed: "😯",
	expressionless: "😑",
	unamused: "😒",
	sweat_smile: "😅",
	sweat: "😓",
	disappointed_relieved: "😥",
	weary: "😩",
	pensive: "😔",
	disappointed: "😞",
	confounded: "😖",
	fearful: "😨",
	cold_sweat: "😰",
	persevere: "😣",
	cry: "😢",
	sob: "😭",
	joy: "😂",
	astonished: "😲",
	scream: "😱",
	tired_face: "😫",
	angry: "😠",
	rage: "😡",
	triumph: "😤",
	sleepy: "😪",
	yum: "😋",
	mask: "😷",
	sunglasses: "😎",
	dizzy_face: "😵",
	imp: "👿",
	smiling_imp: "😈",
	neutral_face: "😐",
	no_mouth: "😶",
	innocent: "😇",
	alien: "👽",
	yellow_heart: "💛",
	blue_heart: "💙",
	purple_heart: "💜",
	heart: "❤️",
	green_heart: "💚",
	broken_heart: "💔",
	heartbeat: "💓",
	heartpulse: "💗",
	two_hearts: "💕",
	revolving_hearts: "💞",
	cupid: "💘",
	sparkling_heart: "💖",
	sparkles: "✨",
	star: "⭐",
	star2: "🌟",
	dizzy: "💫",
	boom: "💥",
	collision: "💥",
	anger: "💢",
	exclamation: "❗",
	question: "❓",
	grey_exclamation: "❕",
	grey_question: "❔",
	zzz: "💤",
	dash: "💨",
	sweat_drops: "💦",
	notes: "🎶",
	musical_note: "🎵",
	fire: "🔥",
	poop: "💩",
	thumbsup: "👍",
	"+1": "👍",
	thumbsdown: "👎",
	"-1": "👎",
	ok_hand: "👌",
	punch: "👊",
	fist: "✊",
	v: "✌️",
	wave: "👋",
	hand: "✋",
	raised_hand: "✋",
	open_hands: "👐",
	point_up: "☝️",
	point_down: "👇",
	point_left: "👈",
	point_right: "👉",
	raised_hands: "🙌",
	pray: "🙏",
	point_up_2: "👆",
	clap: "👏",
	muscle: "💪",
	metal: "🤘",
	fu: "🖕",
	walking: "🚶",
	runner: "🏃",
	running: "🏃",
	couple: "👫",
	family: "👪",
	two_men_holding_hands: "👬",
	two_women_holding_hands: "👭",
	dancer: "💃",
	dancers: "👯",
	ok_woman: "🙆",
	no_good: "🙅",
	information_desk_person: "💁",
	raising_hand: "🙋",
	bride_with_veil: "👰",
	person_with_pouting_face: "🙎",
	person_frowning: "🙍",
	bow: "🙇",
	couplekiss: "💏",
	couple_with_heart: "💑",
	massage: "💆",
	haircut: "💇",
	nail_care: "💅",
	boy: "👦",
	girl: "👧",
	woman: "👩",
	man: "👨",
	baby: "👶",
	older_woman: "👵",
	older_man: "👴",
	person_with_blond_hair: "👱",
	man_with_gua_pi_mao: "👲",
	man_with_turban: "👳",
	construction_worker: "👷",
	cop: "👮",
	angel: "👼",
	princess: "👸",
	smiley_cat: "😺",
	smile_cat: "😸",
	heart_eyes_cat: "😻",
	kissing_cat: "😽",
	smirk_cat: "😼",
	scream_cat: "🙀",
	crying_cat_face: "😿",
	joy_cat: "😹",
	pouting_cat: "😾",
	japanese_ogre: "👹",
	japanese_goblin: "👺",
	see_no_evil: "🙈",
	hear_no_evil: "🙉",
	speak_no_evil: "🙊",
	guardsman: "💂",
	skull: "💀",
	feet: "🐾",
	lips: "👄",
	kiss: "💋",
	droplet: "💧",
	ear: "👂",
	eyes: "👀",
	nose: "👃",
	tongue: "👅",
	love_letter: "💌",
	bust_in_silhouette: "👤",
	busts_in_silhouette: "👥",
	speech_balloon: "💬",
	thought_balloon: "💭",

	// Animals
	dog: "🐶",
	wolf: "🐺",
	cat: "🐱",
	mouse: "🐭",
	hamster: "🐹",
	rabbit: "🐰",
	bear: "🐻",
	panda_face: "🐼",
	koala: "🐨",
	tiger: "🐯",
	lion_face: "🦁",
	cow: "🐮",
	pig: "🐷",
	pig_nose: "🐽",
	frog: "🐸",
	octopus: "🐙",
	monkey_face: "🐵",
	monkey: "🐒",
	chicken: "🐔",
	penguin: "🐧",
	bird: "🐦",
	baby_chick: "🐤",
	hatching_chick: "🐣",
	hatched_chick: "🐥",
	dragon: "🐉",
	dragon_face: "🐲",
	whale: "🐳",
	whale2: "🐋",
	dolphin: "🐬",
	fish: "🐟",
	tropical_fish: "🐠",
	blowfish: "🐡",
	turtle: "🐢",
	snail: "🐌",
	bug: "🐛",
	ant: "🐜",
	bee: "🐝",
	honeybee: "🐝",
	beetle: "🐞",
	shell: "🐚",
	mushroom: "🍄",
	cactus: "🌵",
	palm_tree: "🌴",
	evergreen_tree: "🌲",
	deciduous_tree: "🌳",
	chestnut: "🌰",
	seedling: "🌱",
	blossom: "🌼",
	ear_of_rice: "🌾",
	herb: "🌿",
	four_leaf_clover: "🍀",
	maple_leaf: "🍁",
	fallen_leaf: "🍂",
	leaves: "🍃",
	bouquet: "💐",
	tulip: "🌷",
	rose: "🌹",
	sunflower: "🌻",
	hibiscus: "🌺",
	cherry_blossom: "🌸",
	crocodile: "🐊",
	camel: "🐫",
	dromedary_camel: "🐪",
	leopard: "🐆",
	cat2: "🐈",
	dog2: "🐕",
	poodle: "🐩",
	racehorse: "🐎",
	horse: "🐴",
	ram: "🐏",
	sheep: "🐑",
	goat: "🐐",
	rooster: "🐓",
	turkey: "🦃",
	pig2: "🐖",
	mouse2: "🐁",
	ox: "🐂",
	water_buffalo: "🐃",
	cow2: "🐄",
	tiger2: "🐅",
	rabbit2: "🐇",
	rat: "🐀",
	boar: "🐗",
	elephant: "🐘",
	snake: "🐍",

	// Food & Drink
	apple: "🍎",
	green_apple: "🍏",
	tangerine: "🍊",
	lemon: "🍋",
	cherries: "🍒",
	grapes: "🍇",
	watermelon: "🍉",
	strawberry: "🍓",
	peach: "🍑",
	melon: "🍈",
	banana: "🍌",
	pear: "🍐",
	pineapple: "🍍",
	sweet_potato: "🍠",
	eggplant: "🍆",
	tomato: "🍅",
	corn: "🌽",
	hot_pepper: "🌶️",
	bread: "🍞",
	cheese: "🧀",
	poultry_leg: "🍗",
	meat_on_bone: "🍖",
	fried_shrimp: "🍤",
	egg: "🥚",
	hamburger: "🍔",
	fries: "🍟",
	hotdog: "🌭",
	pizza: "🍕",
	spaghetti: "🍝",
	taco: "🌮",
	burrito: "🌯",
	ramen: "🍜",
	stew: "🍲",
	fish_cake: "🍥",
	sushi: "🍣",
	bento: "🍱",
	curry: "🍛",
	rice_ball: "🍙",
	rice: "🍚",
	rice_cracker: "🍘",
	oden: "🍢",
	dango: "🍡",
	shaved_ice: "🍧",
	ice_cream: "🍨",
	icecream: "🍦",
	cake: "🍰",
	birthday: "🎂",
	custard: "🍮",
	candy: "🍬",
	lollipop: "🍭",
	chocolate_bar: "🍫",
	popcorn: "🍿",
	doughnut: "🍩",
	cookie: "🍪",
	beer: "🍺",
	beers: "🍻",
	wine_glass: "🍷",
	cocktail: "🍸",
	tropical_drink: "🍹",
	champagne: "🍾",
	sake: "🍶",
	tea: "🍵",
	coffee: "☕",
	baby_bottle: "🍼",
	fork_and_knife: "🍴",
	knife_fork_plate: "🍽️",

	// Activities & Sports
	soccer: "⚽",
	basketball: "🏀",
	football: "🏈",
	baseball: "⚾",
	tennis: "🎾",
	volleyball: "🏐",
	rugby_football: "🏉",
	"8ball": "🎱",
	golf: "⛳",
	golfer: "🏌️",
	ping_pong: "🏓",
	badminton: "🏸",
	hockey: "🏒",
	field_hockey: "🏑",
	cricket: "🏏",
	ski: "🎿",
	skier: "⛷️",
	snowboarder: "🏂",
	ice_skate: "⛸️",
	bow_and_arrow: "🏹",
	fishing_pole_and_fish: "🎣",
	rowboat: "🚣",
	swimmer: "🏊",
	surfer: "🏄",
	bath: "🛀",
	basketball_man: "⛹️",
	weight_lifting_man: "🏋️",
	bicyclist: "🚴",
	mountain_bicyclist: "🚵",
	horse_racing: "🏇",
	trophy: "🏆",
	running_shirt_with_sash: "🎽",
	medal: "🏅",
	military_medal: "🎖️",
	reminder_ribbon: "🎗️",
	rosette: "🏵️",
	ticket: "🎫",
	tickets: "🎟️",
	performing_arts: "🎭",
	art: "🎨",
	circus_tent: "🎪",
	microphone: "🎤",
	headphones: "🎧",
	musical_score: "🎼",
	musical_keyboard: "🎹",
	saxophone: "🎷",
	trumpet: "🎺",
	guitar: "🎸",
	violin: "🎻",
	clapper: "🎬",
	video_game: "🎮",
	space_invader: "👾",
	dart: "🎯",
	game_die: "🎲",
	slot_machine: "🎰",
	bowling: "🎳",

	// Travel & Places
	car: "🚗",
	taxi: "🚕",
	blue_car: "🚙",
	bus: "🚌",
	trolleybus: "🚎",
	racing_car: "🏎️",
	police_car: "🚓",
	ambulance: "🚑",
	fire_engine: "🚒",
	minibus: "🚐",
	truck: "🚚",
	articulated_lorry: "🚛",
	tractor: "🚜",
	motorcycle: "🏍️",
	bike: "🚲",
	rotating_light: "🚨",
	oncoming_police_car: "🚔",
	oncoming_bus: "🚍",
	oncoming_automobile: "🚘",
	oncoming_taxi: "🚖",
	aerial_tramway: "🚡",
	mountain_cableway: "🚠",
	suspension_railway: "🚟",
	railway_car: "🚃",
	train: "🚋",
	monorail: "🚝",
	bullettrain_side: "🚄",
	bullettrain_front: "🚅",
	light_rail: "🚈",
	mountain_railway: "🚞",
	steam_locomotive: "🚂",
	train2: "🚆",
	metro: "🚇",
	tram: "🚊",
	station: "🚉",
	helicopter: "🚁",
	airplane: "✈️",
	small_airplane: "🛩️",
	flight_departure: "🛫",
	flight_arrival: "🛬",
	rocket: "🚀",
	satellite: "🛰️",
	seat: "💺",
	anchor: "⚓",
	construction: "🚧",
	fuelpump: "⛽",
	busstop: "🚏",
	vertical_traffic_light: "🚦",
	traffic_light: "🚥",
	checkered_flag: "🏁",
	ship: "🚢",
	ferris_wheel: "🎡",
	roller_coaster: "🎢",
	carousel_horse: "🎠",
	building_construction: "🏗️",
	foggy: "🌁",
	tokyo_tower: "🗼",
	factory: "🏭",
	fountain: "⛲",
	rice_scene: "🎑",
	mountain: "⛰️",
	snow_capped_mountain: "🏔️",
	mount_fuji: "🗻",
	volcano: "🌋",
	japan: "🗾",
	camping: "🏕️",
	tent: "⛺",
	national_park: "🏞️",
	motorway: "🛣️",
	railway_track: "🛤️",
	sunrise: "🌅",
	sunrise_over_mountains: "🌄",
	desert: "🏜️",
	beach_umbrella: "🏖️",
	desert_island: "🏝️",
	city_sunrise: "🌇",
	city_sunset: "🌆",
	cityscape: "🏙️",
	night_with_stars: "🌃",
	bridge_at_night: "🌉",
	milky_way: "🌌",
	stars: "🌠",
	sparkler: "🎇",
	fireworks: "🎆",
	rainbow: "🌈",
	house: "🏠",
	house_with_garden: "🏡",
	school: "🏫",
	office: "🏢",
	post_office: "🏣",
	hospital: "🏥",
	bank: "🏦",
	hotel: "🏨",
	love_hotel: "🏩",
	convenience_store: "🏪",
	department_store: "🏬",
	european_castle: "🏰",
	japanese_castle: "🏯",
	wedding: "💒",
	church: "⛪",
	mosque: "🕌",
	synagogue: "🕍",
	kaaba: "🕋",
	shinto_shrine: "⛩️",

	// Objects
	watch: "⌚",
	iphone: "📱",
	calling: "📲",
	computer: "💻",
	keyboard: "⌨️",
	desktop_computer: "🖥️",
	printer: "🖨️",
	mouse_three_button: "🖱️",
	trackball: "🖲️",
	joystick: "🕹️",
	compression: "🗜️",
	minidisc: "💽",
	floppy_disk: "💾",
	cd: "💿",
	dvd: "📀",
	vhs: "📼",
	camera: "📷",
	camera_with_flash: "📸",
	video_camera: "📹",
	movie_camera: "🎥",
	projector: "📽️",
	film_frames: "🎞️",
	telephone_receiver: "📞",
	telephone: "☎️",
	pager: "📟",
	fax: "📠",
	tv: "📺",
	radio: "📻",
	microphone2: "🎙️",
	level_slider: "🎚️",
	control_knobs: "🎛️",
	stopwatch: "⏱️",
	timer_clock: "⏲️",
	alarm_clock: "⏰",
	clock: "🕰️",
	hourglass: "⌛",
	hourglass_flowing_sand: "⏳",
	satellite_antenna: "📡",
	battery: "🔋",
	electric_plug: "🔌",
	bulb: "💡",
	flashlight: "🔦",
	candle: "🕯️",
	wastebasket: "🗑️",
	oil_drum: "🛢️",
	money_with_wings: "💸",
	dollar: "💵",
	yen: "💴",
	euro: "💶",
	pound: "💷",
	moneybag: "💰",
	credit_card: "💳",
	gem: "💎",
	scales: "⚖️",
	wrench: "🔧",
	hammer: "🔨",
	hammer_and_pick: "⚒️",
	hammer_and_wrench: "🛠️",
	pick: "⛏️",
	nut_and_bolt: "🔩",
	gear: "⚙️",
	chains: "⛓️",
	gun: "🔫",
	bomb: "💣",
	knife: "🔪",
	dagger: "🗡️",
	crossed_swords: "⚔️",
	shield: "🛡️",
	smoking: "🚬",
	coffin: "⚰️",
	funeral_urn: "⚱️",
	amphora: "🏺",
	crystal_ball: "🔮",
	prayer_beads: "📿",
	barber: "💈",
	alembic: "⚗️",
	telescope: "🔭",
	microscope: "🔬",
	hole: "🕳️",
	pill: "💊",
	syringe: "💉",
	thermometer: "🌡️",
	label: "🏷️",
	bookmark: "🔖",
	toilet: "🚽",
	shower: "🚿",
	bathtub: "🛁",
	key: "🔑",
	key2: "🗝️",
	couch_and_lamp: "🛋️",
	sleeping_accommodation: "🛌",
	bed: "🛏️",
	door: "🚪",
	bellhop_bell: "🛎️",
	frame_with_picture: "🖼️",
	world_map: "🗺️",
	parasol_on_ground: "⛱️",
	moyai: "🗿",
	shopping_bags: "🛍️",
	balloon: "🎈",
	flags: "🎏",
	ribbon: "🎀",
	gift: "🎁",
	confetti_ball: "🎊",
	tada: "🎉",
	dolls: "🎎",
	wind_chime: "🎐",
	crossed_flags: "🎌",
	izakaya_lantern: "🏮",
	envelope: "✉️",
	envelope_with_arrow: "📩",
	incoming_envelope: "📨",
	email: "📧",
	"e-mail": "📧",
	postbox: "📮",
	mailbox_closed: "📪",
	mailbox: "📫",
	mailbox_with_mail: "📬",
	mailbox_with_no_mail: "📭",
	package: "📦",
	postal_horn: "📯",
	inbox_tray: "📥",
	outbox_tray: "📤",
	scroll: "📜",
	page_with_curl: "📃",
	bookmark_tabs: "📑",
	bar_chart: "📊",
	chart_with_upwards_trend: "📈",
	chart_with_downwards_trend: "📉",
	page_facing_up: "📄",
	date: "📅",
	calendar: "📆",
	card_index: "📇",
	file_folder: "📁",
	open_file_folder: "📂",
	card_index_dividers: "🗂️",
	file_cabinet: "🗄️",
	newspaper: "📰",
	rolled_up_newspaper: "🗞️",
	notebook: "📓",
	closed_book: "📕",
	green_book: "📗",
	blue_book: "📘",
	orange_book: "📙",
	notebook_with_decorative_cover: "📔",
	ledger: "📒",
	books: "📚",
	book: "📖",
	link: "🔗",
	paperclip: "📎",
	paperclips: "🖇️",
	scissors: "✂️",
	triangular_ruler: "📐",
	straight_ruler: "📏",
	pushpin: "📌",
	round_pushpin: "📍",
	triangular_flag_on_post: "🚩",
	flag_white: "🏳️",
	flag_black: "🏴",
	closed_lock_with_key: "🔐",
	lock: "🔒",
	unlock: "🔓",
	lock_with_ink_pen: "🔏",
	pen_ballpoint: "🖊️",
	pen_fountain: "🖋️",
	black_nib: "✒️",
	pencil: "📝",
	pencil2: "✏️",
	crayon: "🖍️",
	paintbrush: "🖌️",
	mag: "🔍",
	mag_right: "🔎",

	// Symbols
	"100": "💯",
	"1234": "🔢",
	orange_heart: "🧡",
	black_heart: "🖤",
	white_heart: "🤍",
	brown_heart: "🤎",
	heavy_check_mark: "✔️",
	white_check_mark: "✅",
	ballot_box_with_check: "☑️",
	heavy_multiplication_x: "✖️",
	x: "❌",
	negative_squared_cross_mark: "❎",
	heavy_plus_sign: "➕",
	heavy_minus_sign: "➖",
	heavy_division_sign: "➗",
	curly_loop: "➰",
	loop: "➿",
	part_alternation_mark: "〽️",
	eight_spoked_asterisk: "✳️",
	eight_pointed_black_star: "✴️",
	sparkle: "❇️",
	bangbang: "‼️",
	interrobang: "⁉️",
	wavy_dash: "〰️",
	copyright: "©️",
	registered: "®️",
	tm: "™️",
	warning: "⚠️",
	radioactive: "☢️",
	biohazard: "☣️",
	no_entry: "⛔",
	no_entry_sign: "🚫",
	name_badge: "📛",
	no_pedestrians: "🚷",
	no_mobile_phones: "📵",
	underage: "🔞",
	no_smoking: "🚭",
	recycle: "♻️",
	fleur_de_lis: "⚜️",
	trident: "🔱",
	beginner: "🔰",
	o: "⭕",
	white_circle: "⚪",
	black_circle: "⚫",
	red_circle: "🔴",
	large_blue_circle: "🔵",
	small_orange_diamond: "🔸",
	small_blue_diamond: "🔹",
	large_orange_diamond: "🔶",
	large_blue_diamond: "🔷",
	small_red_triangle: "🔺",
	small_red_triangle_down: "🔻",
	diamond_shape_with_a_dot_inside: "💠",
	radio_button: "🔘",
	black_square_button: "🔲",
	white_square_button: "🔳",
	black_small_square: "▪️",
	white_small_square: "▫️",
	black_medium_small_square: "◾",
	white_medium_small_square: "◽",
	black_medium_square: "◼️",
	white_medium_square: "◻️",
	black_large_square: "⬛",
	white_large_square: "⬜",
	speaker: "🔈",
	mute: "🔇",
	sound: "🔉",
	loud_sound: "🔊",
	bell: "🔔",
	no_bell: "🔕",
	mega: "📣",
	loudspeaker: "📢",
	eye_in_speech_bubble: "👁️‍🗨️",
	right_anger_bubble: "🗯️",
	spades: "♠️",
	clubs: "♣️",
	hearts: "♥️",
	diamonds: "♦️",
	black_joker: "🃏",
	flower_playing_cards: "🎴",
	mahjong: "🀄",

	// Clocks
	clock1: "🕐",
	clock2: "🕑",
	clock3: "🕒",
	clock4: "🕓",
	clock5: "🕔",
	clock6: "🕕",
	clock7: "🕖",
	clock8: "🕗",
	clock9: "🕘",
	clock10: "🕙",
	clock11: "🕚",
	clock12: "🕛",

	// Flags (common ones)
	flag_se: "🇸🇪",
	flag_us: "🇺🇸",
	flag_gb: "🇬🇧",
	flag_de: "🇩🇪",
	flag_fr: "🇫🇷",
	flag_es: "🇪🇸",
	flag_it: "🇮🇹",
	flag_jp: "🇯🇵",
	flag_cn: "🇨🇳",
	flag_kr: "🇰🇷",
	flag_no: "🇳🇴",
	flag_dk: "🇩🇰",
	flag_fi: "🇫🇮",

	// Work/Office
	briefcase: "💼",
	notepad_spiral: "🗒️",
	spiral_calendar: "🗓️",
	clipboard: "📋",

	// Tech
	laptop: "💻",
	computer_mouse: "🖱️",

	// Misc commonly used
	party_popper: "🎉",
	christmas_tree: "🎄",
	jack_o_lantern: "🎃",
	ghost: "👻",
	santa: "🎅",
	snowman: "☃️",
	snowflake: "❄️",
	sunny: "☀️",
	partly_sunny: "⛅",
	cloud: "☁️",
	rain_cloud: "🌧️",
	thunder_cloud_and_rain: "⛈️",
	umbrella: "☂️",
	zap: "⚡",
	ocean: "🌊",
	earth_africa: "🌍",
	earth_americas: "🌎",
	earth_asia: "🌏",
	globe_with_meridians: "🌐",
	new_moon: "🌑",
	full_moon: "🌕",
	crescent_moon: "🌙",
	comet: "☄️",
	robot: "🤖",
	brain: "🧠",
	eye: "👁️",
	thinking: "🤔",
	shrug: "🤷",
	raised_eyebrow: "🤨",
	monocle_face: "🧐",
	nerd_face: "🤓",
	partying_face: "🥳",
	hot_face: "🥵",
	cold_face: "🥶",
	woozy_face: "🥴",
	crossed_fingers: "🤞",
	handshake: "🤝",
	writing_hand: "✍️",
	selfie: "🤳",
	nail_polish: "💅",
	ring: "💍",
	lipstick: "💄",
	crown: "👑",
	womans_hat: "👒",
	tophat: "🎩",
	mortar_board: "🎓",
	billed_cap: "🧢",
	military_helmet: "🪖",
	rescue_worker_helmet: "⛑️",
	glasses: "👓",
	dark_sunglasses: "🕶️",
	goggles: "🥽",
	lab_coat: "🥼",
	safety_vest: "🦺",
	necktie: "👔",
	shirt: "👕",
	jeans: "👖",
	scarf: "🧣",
	gloves: "🧤",
	coat: "🧥",
	socks: "🧦",
	dress: "👗",
	kimono: "👘",
	sari: "🥻",
	one_piece_swimsuit: "🩱",
	briefs: "🩲",
	shorts: "🩳",
	bikini: "👙",
	womans_clothes: "👚",
	purse: "👛",
	handbag: "👜",
	pouch: "👝",
	shopping: "🛍️",
	backpack: "🎒",
	mans_shoe: "👞",
	athletic_shoe: "👟",
	hiking_boot: "🥾",
	flat_shoe: "🥿",
	high_heel: "👠",
	sandal: "👡",
	ballet_shoes: "🩰",
	boot: "👢",
};

// Custom emoji map (name -> URL or alias)
let customEmojiMap: Record<string, string> = {};

/**
 * Set the custom emoji map (fetched from Slack).
 * Call this before converting text to populate custom emojis.
 */
export function setCustomEmojis(emojis: Record<string, string>): void {
	customEmojiMap = emojis;
	console.log(`  🎨 Loaded ${Object.keys(emojis).length} custom emojis`);
}

/**
 * Convert emoji shortcodes (like :smile:) to Unicode emojis or images.
 *
 * @param text - Text containing emoji shortcodes
 * @returns Text with shortcodes converted to Unicode emojis or img tags
 */
export function convertEmojiShortcodes(text: string): string {
	return text.replace(/:([a-zA-Z0-9_+-]+):/g, (match, shortcode) => {
		const lowerCode = shortcode.toLowerCase();

		// Check standard emoji map first
		const standardEmoji = EMOJI_MAP[lowerCode];
		if (standardEmoji) {
			return standardEmoji;
		}

		// Check custom emojis
		const customEmoji = customEmojiMap[lowerCode];
		if (customEmoji) {
			// Handle aliases (e.g., "alias:thumbsup")
			if (customEmoji.startsWith("alias:")) {
				const aliasTarget = customEmoji.slice(6);
				const aliasEmoji = EMOJI_MAP[aliasTarget];
				return aliasEmoji || match;
			}

			// It's a URL - render as inline image
			return `<img src="${customEmoji}" alt="${shortcode}" class="inline-emoji" style="height: 1.2em; width: 1.2em; vertical-align: middle; display: inline-block;">`;
		}

		// Return original if not found
		return match;
	});
}

/**
 * Process all text content in an object, converting emoji shortcodes.
 * Recursively processes nested objects and arrays.
 */
export function convertEmojisInObject<T>(obj: T): T {
	if (typeof obj === "string") {
		return convertEmojiShortcodes(obj) as T;
	}

	if (Array.isArray(obj)) {
		return obj.map((item) => convertEmojisInObject(item)) as T;
	}

	if (obj !== null && typeof obj === "object") {
		const result: Record<string, unknown> = {};
		for (const [key, value] of Object.entries(obj)) {
			result[key] = convertEmojisInObject(value);
		}
		return result as T;
	}

	return obj;
}
